create or replace package sct_test
  authid definer
as

  /* generated by utPLSQL for SQL Developer on 2019-07-07 10:54:10 */

  -- %suite(sct_test)
  -- %suitepath(alltests)
  -- %rollback(manual)

  -- %beforeall (Test Suite initialisieren)
  procedure tear_up;
  
  -- %aftereach
  procedure persist_outcome;
  
  -- %test (Render Plugin)
  procedure render_plugin;
  
  -- %test (Refresh Plugin)
  procedure refresh_plugin;

  -- %test
  procedure get_char;

  -- %test
  procedure get_char_default;

  -- %test
  procedure get_date;

  -- %test
  procedure get_event;

  -- %test
  procedure get_firing_item;

  -- %test
  procedure get_number;

  -- %test
  procedure add_javascript;

  -- %test
  procedure check_date;

  -- %test
  procedure check_mandatory;

  -- %test
  procedure check_number;

  -- %test
  procedure exclusive_or;

  -- %test
  procedure execute_javascript;

  -- %test
  procedure execute_plsql;

  -- %test
  procedure has_errors;

  -- %test
  procedure has_no_errors;

  -- %test
  procedure not_null;

  -- %test
  procedure notify;

  -- %test
  procedure register_error;

  -- %test
  procedure register_mandatory;

  -- %test
  procedure register_notification;

  -- %test
  procedure set_list_from_stmt;

  -- %test
  procedure set_session_state;

  -- %test
  procedure set_session_state_or_error;

  -- %test
  procedure set_value_from_stmt;

  -- %test
  procedure stop_rule;

  -- %test
  procedure validate_page;

  -- %test
  procedure toggle_item_mandatory;

  -- %test
  procedure toggle_item_status;

  -- %test
  procedure toggle_item_visibility;

  -- %test
  procedure refresh_item;

  -- %test
  procedure set_item;

  -- %test
  procedure set_focus;

  -- %test
  procedure execute_apex_action;

  -- %test
  procedure execute_java_script;

  -- %test
  procedure write_to_console;

  -- %afterall (Test Suite herunterfahren)
  procedure tear_down;

end sct_test;
/
